# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/egor/my-projects/data-compression-algos

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/egor/my-projects/data-compression-algos

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/egor/my-projects/data-compression-algos/CMakeFiles /home/egor/my-projects/data-compression-algos/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/egor/my-projects/data-compression-algos/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

#=============================================================================
# Target rules for targets named dca

# Build rule for target.
dca: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dca
.PHONY : dca

# fast build rule for target.
dca/fast:
	$(MAKE) -f CMakeFiles/dca.dir/build.make CMakeFiles/dca.dir/build
.PHONY : dca/fast

src/arithmetic/range.o: src/arithmetic/range.cpp.o

.PHONY : src/arithmetic/range.o

# target to build an object file
src/arithmetic/range.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/arithmetic/range.cpp.o
	$(MAKE) -f CMakeFiles/dca.dir/build.make CMakeFiles/dca.dir/src/arithmetic/range.cpp.o
.PHONY : src/arithmetic/range.cpp.o

src/arithmetic/range.i: src/arithmetic/range.cpp.i

.PHONY : src/arithmetic/range.i

# target to preprocess a source file
src/arithmetic/range.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/arithmetic/range.cpp.i
	$(MAKE) -f CMakeFiles/dca.dir/build.make CMakeFiles/dca.dir/src/arithmetic/range.cpp.i
.PHONY : src/arithmetic/range.cpp.i

src/arithmetic/range.s: src/arithmetic/range.cpp.s

.PHONY : src/arithmetic/range.s

# target to generate assembly for a file
src/arithmetic/range.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/arithmetic/range.cpp.s
	$(MAKE) -f CMakeFiles/dca.dir/build.make CMakeFiles/dca.dir/src/arithmetic/range.cpp.s
.PHONY : src/arithmetic/range.cpp.s

src/bit_manipulating.o: src/bit_manipulating.cpp.o

.PHONY : src/bit_manipulating.o

# target to build an object file
src/bit_manipulating.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/bit_manipulating.cpp.o
	$(MAKE) -f CMakeFiles/dca.dir/build.make CMakeFiles/dca.dir/src/bit_manipulating.cpp.o
.PHONY : src/bit_manipulating.cpp.o

src/bit_manipulating.i: src/bit_manipulating.cpp.i

.PHONY : src/bit_manipulating.i

# target to preprocess a source file
src/bit_manipulating.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/bit_manipulating.cpp.i
	$(MAKE) -f CMakeFiles/dca.dir/build.make CMakeFiles/dca.dir/src/bit_manipulating.cpp.i
.PHONY : src/bit_manipulating.cpp.i

src/bit_manipulating.s: src/bit_manipulating.cpp.s

.PHONY : src/bit_manipulating.s

# target to generate assembly for a file
src/bit_manipulating.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/bit_manipulating.cpp.s
	$(MAKE) -f CMakeFiles/dca.dir/build.make CMakeFiles/dca.dir/src/bit_manipulating.cpp.s
.PHONY : src/bit_manipulating.cpp.s

src/huffman/huffman_coding.o: src/huffman/huffman_coding.cpp.o

.PHONY : src/huffman/huffman_coding.o

# target to build an object file
src/huffman/huffman_coding.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/huffman/huffman_coding.cpp.o
	$(MAKE) -f CMakeFiles/dca.dir/build.make CMakeFiles/dca.dir/src/huffman/huffman_coding.cpp.o
.PHONY : src/huffman/huffman_coding.cpp.o

src/huffman/huffman_coding.i: src/huffman/huffman_coding.cpp.i

.PHONY : src/huffman/huffman_coding.i

# target to preprocess a source file
src/huffman/huffman_coding.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/huffman/huffman_coding.cpp.i
	$(MAKE) -f CMakeFiles/dca.dir/build.make CMakeFiles/dca.dir/src/huffman/huffman_coding.cpp.i
.PHONY : src/huffman/huffman_coding.cpp.i

src/huffman/huffman_coding.s: src/huffman/huffman_coding.cpp.s

.PHONY : src/huffman/huffman_coding.s

# target to generate assembly for a file
src/huffman/huffman_coding.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/huffman/huffman_coding.cpp.s
	$(MAKE) -f CMakeFiles/dca.dir/build.make CMakeFiles/dca.dir/src/huffman/huffman_coding.cpp.s
.PHONY : src/huffman/huffman_coding.cpp.s

src/huffman/huffman_tree.o: src/huffman/huffman_tree.cpp.o

.PHONY : src/huffman/huffman_tree.o

# target to build an object file
src/huffman/huffman_tree.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/huffman/huffman_tree.cpp.o
	$(MAKE) -f CMakeFiles/dca.dir/build.make CMakeFiles/dca.dir/src/huffman/huffman_tree.cpp.o
.PHONY : src/huffman/huffman_tree.cpp.o

src/huffman/huffman_tree.i: src/huffman/huffman_tree.cpp.i

.PHONY : src/huffman/huffman_tree.i

# target to preprocess a source file
src/huffman/huffman_tree.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/huffman/huffman_tree.cpp.i
	$(MAKE) -f CMakeFiles/dca.dir/build.make CMakeFiles/dca.dir/src/huffman/huffman_tree.cpp.i
.PHONY : src/huffman/huffman_tree.cpp.i

src/huffman/huffman_tree.s: src/huffman/huffman_tree.cpp.s

.PHONY : src/huffman/huffman_tree.s

# target to generate assembly for a file
src/huffman/huffman_tree.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/huffman/huffman_tree.cpp.s
	$(MAKE) -f CMakeFiles/dca.dir/build.make CMakeFiles/dca.dir/src/huffman/huffman_tree.cpp.s
.PHONY : src/huffman/huffman_tree.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/dca.dir/build.make CMakeFiles/dca.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/dca.dir/build.make CMakeFiles/dca.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/dca.dir/build.make CMakeFiles/dca.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/statistic.o: src/statistic.cpp.o

.PHONY : src/statistic.o

# target to build an object file
src/statistic.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/statistic.cpp.o
	$(MAKE) -f CMakeFiles/dca.dir/build.make CMakeFiles/dca.dir/src/statistic.cpp.o
.PHONY : src/statistic.cpp.o

src/statistic.i: src/statistic.cpp.i

.PHONY : src/statistic.i

# target to preprocess a source file
src/statistic.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/statistic.cpp.i
	$(MAKE) -f CMakeFiles/dca.dir/build.make CMakeFiles/dca.dir/src/statistic.cpp.i
.PHONY : src/statistic.cpp.i

src/statistic.s: src/statistic.cpp.s

.PHONY : src/statistic.s

# target to generate assembly for a file
src/statistic.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/statistic.cpp.s
	$(MAKE) -f CMakeFiles/dca.dir/build.make CMakeFiles/dca.dir/src/statistic.cpp.s
.PHONY : src/statistic.cpp.s

src/test.o: src/test.cpp.o

.PHONY : src/test.o

# target to build an object file
src/test.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/test.cpp.o
.PHONY : src/test.cpp.o

src/test.i: src/test.cpp.i

.PHONY : src/test.i

# target to preprocess a source file
src/test.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/test.cpp.i
.PHONY : src/test.cpp.i

src/test.s: src/test.cpp.s

.PHONY : src/test.s

# target to generate assembly for a file
src/test.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/test.cpp.s
.PHONY : src/test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... test"
	@echo "... dca"
	@echo "... src/arithmetic/range.o"
	@echo "... src/arithmetic/range.i"
	@echo "... src/arithmetic/range.s"
	@echo "... src/bit_manipulating.o"
	@echo "... src/bit_manipulating.i"
	@echo "... src/bit_manipulating.s"
	@echo "... src/huffman/huffman_coding.o"
	@echo "... src/huffman/huffman_coding.i"
	@echo "... src/huffman/huffman_coding.s"
	@echo "... src/huffman/huffman_tree.o"
	@echo "... src/huffman/huffman_tree.i"
	@echo "... src/huffman/huffman_tree.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/statistic.o"
	@echo "... src/statistic.i"
	@echo "... src/statistic.s"
	@echo "... src/test.o"
	@echo "... src/test.i"
	@echo "... src/test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

